title: Kiana Dane's Research
description: Academic publications and research projects
baseurl: "" 
url: "https://kianadane.github.io"

remote_theme: "mmistakes/minimal-mistakes"

sass:
  style: compressed
  
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

author:
  name: "Kiana Dane"
  avatar: "/assets/images/avatar.jpg"
  bio: "Data scientist and researcher. Passionate about AI and ethics."

nav:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
