title: Kiana Dane's Research
description: Academic publications and research projects
baseurl: "" 
url: "https://kianadane.github.io"

remote_theme: "mmistakes/minimal-mistakes"

sass:
  style: compressed
  
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:path/


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: splash
      header:
        overlay_color: "#000"
        overlay_filter: "0.3"

author:
  name: "Kiana Dane"
  avatar: "/assets/images/avatar.png"
  bio: "Data scientist | Geospatial AI | Ethics & ML"
  location: "Charlottesville, VA"
  email: "kianadane@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/kianadane"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/kiana-dane"

nav:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
